name: firebase_internal
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/fluttercommunity/firebase_flutter_sdk
author: long1eu <home@long1.eu>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  firebase_common:
    git:
      url: https://github.com/fluttercommunity/firebase_dart_sdk
      path: firebase_common
  hive: ^1.4.1+1

dev_dependencies:
  test: ^1.12.0
