name: vm_example
description: Firestore example for VM
version: 0.0.1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  crypto: ^2.1.2
  googleapis_auth: ^0.2.10
  dart_sqlite:
    git:
      url: https://github.com/long1eu/dart_sqlite
      path: dart
  firebase_common:
    git:
      url: https://github.com/fluttercommunity/firebase_dart_sdk
      path: firebase_common
  firebase_firestore:
    git:
      url: https://github.com/fluttercommunity/firebase_dart_sdk
      path: firebase_firestore 
