name: firebase_auth
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: long1eu <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  firebase_common:
    path: ../firebase_common 

dev_dependencies:
  test: ^1.0.0
