name: firebase_database_collection
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com
# author: long1eu <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
  dart_quickcheck:
    path: /Users/long1eu/IdeaProjects/dart_quickcheck