name: cloud_firestore_dart
description: Dart implementation of cloud_firestore using cloud_firestore_vm
version: 0.0.1
homepage: https://github.com/fluttercommunity/firebase_dart_sdk/tree/develop/cloud_firestore/cloud_firestore_dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore_platform_interface: ^1.1.0
  cloud_firestore_vm: ^0.0.5
  firebase_core: ^0.4.4+3
  firebase_core_vm: ^0.0.4
  path_provider: ^1.6.5
  meta: ^1.1.8
  cloud_firestore_web: ^0.1.1+2
  sqflite: ^1.3.0
  moor_ffi: ^0.4.0
